language: bash

install:
 - make install

before_script:
 - . ~/.bashrc

script: 
 - touch foo~
 - rmold
 - if [ -e foo~ ]; then exit 1; fi; 
 - echo hello > ~/testfile
 - rmtrailws ~/testfile

after_script:
 - make uninstall
